check if commit-msg hook is installed
Change-Id: Ia3bebcb53c5cc8b28223c834f40be1db50674e51

diff --git a/git-gerrit-change-ids b/git-gerrit-change-ids
--- a/git-gerrit-change-ids
+++ b/git-gerrit-change-ids
@@ -21,6 +21,11 @@ set -o nounset
 
 require_work_tree
 
+if [ ! -f "${GIT_DIR}/hooks/commit-msg" ]; then
+    echo 'ERROR: commit-msg hook not installed, have you run `git gerrit init`?'
+    exit 1
+fi
+
 # set GIT_EDITOR=true because we can't --exec without --interactive but we
 # don't really want to be --interactive
 GIT_EDITOR=true git rebase --interactive \
