change option names
Change-Id: I471dd2fdddb0bcca4b140c1034e112943db57b6f

diff --git a/git-gerrit-init b/git-gerrit-init
--- a/git-gerrit-init
+++ b/git-gerrit-init
@@ -3,17 +3,17 @@
 set -o errexit
 set -o pipefail
 
-host_default=apipe-review.gsc.wustl.edu
+url_default=apipe-review.gsc.wustl.edu
 port_default=29418
-remote_default=origin
+remote_name_default=origin
 
 OPTS_SPEC="\
 git gerrit init <gerrit_project>
 --
-h                   show the help
-p,port=             port (defaults to ${port_default})
-H,host=             host (defaults to ${host_default})
-r,remote=           remote name (defaults to ${remote_default})
+h                 show the help
+p,port=           port (defaults to ${port_default})
+u,url=            url (defaults to ${url_default})
+n,name=           remote name (defaults to ${remote_name_default})
 "
 
 eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"
@@ -28,21 +28,21 @@ while [ $# -gt 0 ]; do
     shift
     case "$opt" in
         -p|--port) port="$1"; shift ;;
-        -H|--host) host="$1"; shift ;;
-        -r|--remote) remote="$1"; shift ;;
+        -u|--url) url="$1"; shift ;;
+        -n|--name) remote_name="$1"; shift ;;
         --) break ;;
         *) die "Unexpected option: $opt" ;;
     esac
 done
 
-if [ -z "$host" ]; then
-    host=$host_default
+if [ -z "$url" ]; then
+    url=$url_default
 fi
 if [ -z "$port" ]; then
     port=$port_default
 fi
-if [ -z "$remote" ]; then
-    remote=$remote_default
+if [ -z "$remote_name" ]; then
+    remote_name=$remote_name_default
 fi
 
 if [ -z "$1" ]; then
@@ -54,26 +54,26 @@ fi
 
 set -o nounset
 
-url=ssh://${host}:${port}/${repo}
-if git config remote.${remote}.url 1> /dev/null; then
-    current_url=$(git config remote.${remote}.url)
+url=ssh://${url}:${port}/${repo}
+if git config remote.${remote_name}.url 1> /dev/null; then
+    current_url=$(git config remote.${remote_name}.url)
     if [ "${current_url}" != "${url}" ]; then
-        old_remote=old-${remote}
-        if ! git config remote.${old_remote}.url; then
-            die "ERROR: Cannot backup old ${remote} as '${old_remote}' because it already exists."
+        old_remote_name=old-${remote_name}
+        if ! git config remote.${old_remote_name}.url; then
+            die "ERROR: Cannot backup old ${remote_name} as '${old_remote_name}' because it already exists."
         fi
-        git remote add ${old_remote} ${current_url}
-        git remote set-url ${remote} ${url}
+        git remote add ${old_remote_name} ${current_url}
+        git remote set-url ${remote_name} ${url}
     fi
 else
-    git remote add ${remote} ${url}
+    git remote add ${remote_name} ${url}
 fi
 
-git config remote.${remote}.push +refs/heads/*:refs/for/*
+git config remote.${remote_name}.push +refs/heads/*:refs/for/*
 
 hook=${GIT_DIR}/hooks/commit-msg
 tmp_hook=$TMPDIR/commit-msg.$$
-scp -p -P ${port} ${host}:hooks/commit-msg ${tmp_hook}
+scp -p -P ${port} ${url}:hooks/commit-msg ${tmp_hook}
 if [ -f "${GIT_DIR}/hooks/commit-msg" ]; then
     if ! cmp --silent ${tmp_hook} ${hook}; then
         say "Warning: Skipping commit-msg hook install since one already exists."
