catch scp failures and produce error
Change-Id: Iebdfc5bd06d0ae8cf97ec7aaefe7540c9818b236

diff --git a/git-gerrit-init b/git-gerrit-init
--- a/git-gerrit-init
+++ b/git-gerrit-init
@@ -73,7 +73,10 @@ git config remote.${remote_name}.push +refs/heads/*:refs/for/*
 
 hook=${GIT_DIR}/hooks/commit-msg
 tmp_hook=$TMPDIR/commit-msg.$$
-scp -q -p -P ${port} ${url}:hooks/commit-msg ${tmp_hook}
+
+scp -q -p -P ${port} ${url}:hooks/commit-msg ${tmp_hook} \
+    || die "ERROR: Could not get commit-msg hook from server: $url"
+
 if [ -f "${GIT_DIR}/hooks/commit-msg" ]; then
     if ! cmp --silent ${tmp_hook} ${hook}; then
         say "Warning: Skipping commit-msg hook install since one already exists."
